[package]
name = "solidity"
version = "0.1.0"
authors = ["Daniel Akhterov <akhterovd@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
bigint = { version = "4.4.1", default-features = false, optional = true }
sha3 = "0.8.2"
hex = "0.4.0"

[features]
U256 = [ "bigint" ]
