[workspace]
members = [
    ".",
    "solidity-core",
    "solidity-derive",
    "examples/contract-call"
]

[package]
name = "solidity"
version = "0.1.0"
authors = ["Daniel Akhterov <akhterovd@gmail.com>"]
edition = "2018"

[dependencies]
solidity-derive = { path = "solidity-derive", optional = true }
solidity-core = { path = "solidity-core", default-features = false }

[features]
default = [ "serde", "derive" ]

serde = [ "solidity-core/derive" ]

derive = [ "solidity-derive" ]

nightly = [ "solidity-core/nightly" ]

bigint = [ "solidity-core/bigint" ]

# fixed = [ "solidity-core/fixedmxn" ]
