[package]
name = "solidity"
version = "0.1.0"
authors = ["Daniel Akhterov <akhterovd@gmail.com>"]
edition = "2018"
members = [ "solidity-core", "solidity-derive" ]

[dependencies]
solidity-derive = { path = "solidity-derive", optional = true }
solidity-core = { path = "solidity-core", default-features = false }

[features]
default = [ "serde", "derive" ]

serde = [ "solidity-core/derive" ]

derive = [ "solidity-derive" ]