[package]
name = "cargo-solid-example"
version = "0.1.0"
edition = "2018"
workspace = "../.."

[dependencies]
solid = { path = "../..", features = [ "derive", "bigint" ]}
serde = "1.0.104"
num-bigint = "0.2.6"
